name: DBNet
dataset:
  train:
    dataset:
      type: ICDAR2015Dataset  # ✅ 保留数据集类型
      args:
        data_path:
          - /data1/cxy/sodbnet2015/train.txt  # ✅ 存 (雪图, 去雪图, GT)
        pre_processes:
          - type: IaaAugment
            args:
              - {'type': Fliplr, 'args': {'p': 0.5}}
              - {'type': Affine, 'args': {'rotate': [-10, 10]}}
              - {'type': Resize, 'args': {'size': [0.5, 3]}}
          - type: EastRandomCropData
            args:
              size: [640,640]
              max_tries: 50
              keep_ratio: true
          - type: MakeBorderMap
            args:
              shrink_ratio: 0.4
              thresh_min: 0.3
              thresh_max: 0.7
          - type: MakeShrinkMap
            args:
              shrink_ratio: 0.4
              min_text_size: 8
        transforms:
          - type: ToTensor
            args: {}
          - type: Normalize
            args:
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
        img_mode: RGB
        filter_keys: []  # ✅ 不过滤关键数据
        ignore_tags: ['###']
    loader:
      batch_size: 1  # ✅ 增大 batch_size
      shuffle: true
      pin_memory: true
      num_workers: 6
      collate_fn: DualImageCollateFN  # ✅ 适配双输入

  validate:
    dataset:
      type: ICDAR2015Dataset
      args:
        data_path:
          - '/data1/cxy/sodbnet2015/test.txt'  # ✅ 存 (雪图, 去雪图, GT)
        pre_processes:
          - type: ResizeShortSize
            args:
              short_size: 736
              resize_text_polys: false
        transforms:
          - type: ToTensor
            args: {}
          - type: Normalize
            args:
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
        img_mode: RGB
        filter_keys: []
        ignore_tags: ['*', '###']
    loader:
      batch_size: 1
      shuffle: false
      pin_memory: false
      num_workers: 6
      collate_fn: DualImageCollateFN  # ✅ 适配双输入
